### ISSUE TITLE
Request to join the bootstrap governance board

### ISSUE THREAD

**Issue by AloisReitbauer** [open-feature/community#100]
I am offering to join the bootstrap governance board for one of the open seats and help establishing a governance process based on experience in other projects. 

My key goals:
* Establish and run regular governance meetings
* Establish an enhancement process. 
* Help to define the charter for the coming year
* Support GB, TC and maintainers on establishing the roadmap for the next 12 months
* Help to build an end-user outreach group.

I have been working intensely on OpenFeature and helped assemble the project team. I would like to make my contribution more official also representing one of the major contributing organisations. 

If you support please add your +1 below. Thank you!

**Comment by AlexsJones** [comment]
I am a little confused by the wording - are you implying a governance board already exists?
If so I missed the memo here. I would also like to join the board and feel very strongly that we have proportional representation.

**Comment by toddbaert** [comment]
@AlexsJones the governance board has existed since April, which I believe predates your involvement. That might be why this is news to you.

https://github.com/open-feature/community/blob/f12797a8b1e36b35383307732cdc4f9783cdcddf/governance-charter.md

**Comment by toddbaert** [comment]
Took a bit of digging but here's the original vote for reference: https://github.com/open-feature/community/issues/47

IIRC there's a 1 year term.

**Comment by AlexsJones** [comment]
> @AlexsJones the governance board has existed since April, which I believe just slightly predates your involvement. That might be why this is the first you're hearing about it.
> 
> https://github.com/open-feature/community/blob/f12797a8b1e36b35383307732cdc4f9783cdcddf/governance-charter.md

oh haha, yes that would probably be why!

**Comment by AloisReitbauer** [comment]
Let's decouple some topics of this thread:
* Alex, yes you should be on the governance board. There are currently two open seats. However, you will not be able to be on the governance and technical board
* The fact that you don't know about the board, shows that it needs to get more active :-) 
* I will take on the representation for Dynatrace. If anybody is "worried" that Dynatrace has two people on the board we can bring this down to 1. 

The next board election is up in the next six months. My goal is to support the process until then.

**Comment by justinabrahms** [comment]
Our board doesn't have much activity at the moment. To the degree you plan to change that, I support your involvement.

**Comment by oleg-nenashev** [comment]
+1 non-binding
From the process perspective, if @AloisReitbauer joins I would recommend adding the 7th member so that we keep the odd number. At the same time, it is not a blocker since we do not have any formal votes planned
