### ISSUE TITLE
🎃 Hacktoberfest Prep 🎃

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/community#101]
## Hacktoberfest prep

[Hacktoberfest](https://hacktoberfest.com/) is an annual event that promotes open source participation. OpenFeature would like to support this initiative by offering guidance for contributing to the project. One of the best ways to get involved would be to develop hooks and providers in various contributing repos.

### Proposal

In order for a repo to participate the `hacktoberfest` topic must be set. This should be done in the following repos:

- [ ] js-contrib
- [ ] java-contrib
- [ ] go-contrib

For SDKs without associated contribs repos, we could create issue to have the community help bootstrap them. Eligible SDKs include:

  - [ ] PHP
  - [ ] Python
  - [ ] .NET

As per the [Hacktoberfest maintainers guidelines](https://hacktoberfest.com/participation/#maintainers), the following requirements must be met per participating repository:

- Apply the “hacktoberfest” label to issues you want contributors to help with in your GitHub or GitLab project.
- Add a CONTRIBUTING.md file with contribution guidelines to your repository.

Taking into account the requirements, the following user journey could be implemented in contrib repos. This would allow participants to submit proposals for adding new hooks and providers.

1. Go to repo
1. Open pinned Hacktoberfest issue
1. Create issue using Hacktoberfest issue templates (hooks, providers)
1. New issue is created with "pending-acceptance" 
1. Repo maintainer reviews issue. If approved, "pending-acceptance" label is removed, "hacktoberfest" label is added, reporter is assigned. 
1. PR is reviewed. If approved, the PR is merged or `hacktoberfest-accepted` is added. In case of [spam](https://hacktoberfest.com/participation/#maintainers), the PR is closed and the label `spam` is added.

### How OpenFeature maintainers can help

Volunteer to review Hacktoberfest issues and PRs. Please reply with a comment below with the language(s) you're willing to support in reviewing. Together we can take this great opportunity to expand our community and the feature flagging ecosystem overall!

**Comment by toddbaert** [comment]
If you have other specific issues that you believe are good candidates, feel free to add a "hacktoberfest" label to them, keeping in mind the [maintainer's guidelines](https://hacktoberfest.com/participation/#maintainers).

**Comment by toddbaert** [comment]
I volunteer to review issues and PRs in `TS/JS`, `Java` or `.NET`.

**Comment by justinabrahms** [comment]
I'm happy to review python, go and java.

In addition to providers and hooks, I think it would be good to have examples in popular web frameworks (spring boot, etc).. especially as tutorials/blogs.

**Comment by DavidPHirsch** [comment]
@toddbaert @justinabrahms  and @beeme1mr did we get any participation here? I guess we can close this tomorrow
