### ISSUE TITLE
Request to join the bootstrap governance board

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/community#104]
I would like to nominate myself as a candidate to join the bootstrap governance board.
(Thanks @AloisReitbauer for the reminder to apply here! ) 

### Relevant prior-art

- I bring commercial & technical experience to the Open Feature project to achieve wider adoption and success.
- I am the author of [flagD](https://github.com/open-feature/flagd) and [Open feature operator](https://github.com/open-feature/open-feature-operator) and now actively maintain these with the community. 
- I am actively participating in the wider cloud ecosystem and am looking for collaborative opportunities for us to enable solutions for real-world problems.

### Goals

- Establish and run regular governance meetings
- Establish an enhancement process.
- Help to define the charter for the coming year
- Support GB, TC and maintainers on establishing the roadmap for the next 12 months
- Help to build an end-user outreach group.

If you would like to support my nomination, please add your +1 below. Thank you!

**Comment by oleg-nenashev** [comment]
+1 non-binding. Alex has been a super active in the community, especially around flagd and integrations. It would be great to have him onboard

**Comment by toddbaert** [comment]
+1 from me as well! Can't give enough credit to @AlexsJones especially when it comes to the "cloud-native" aspects of OpenFeature.

**Comment by benjiro** [comment]
+1 here. @AlexsJones has been instrumental in the cloud-native areas and active in the community. He would be a welcome addition to the governance board. 🏆

**Comment by thschue** [comment]
+1 non-binding from me. @AlexsJones is very active and brought a lot of his knowledge and experience to the project.

**Comment by AloisReitbauer** [comment]
+1 binding

**Comment by beeme1mr** [comment]
+1 binding

**Comment by moredip** [comment]
+1 binding

**Comment by justinabrahms** [comment]
Isn't this decided by now? +1 binding.

**Comment by AloisReitbauer** [comment]
Not really. But it should be

**Comment by AlexsJones** [comment]
I would love to be able to have a decision this week if you folks are okay with that - I am presenting OpenFeature in it's premiere on Friday and would like to know whether I can speak a little to what we want to do as a community/GB.

**Comment by toddbaert** [comment]
It appears we have a consensus https://github.com/open-feature/community/blob/main/governance-charter.md#decision-making. There's not been a single objection.

I propose we add @AlexsJones to this PR: https://github.com/open-feature/community/pull/112/files by @AloisReitbauer , then we can close this issue.

**Comment by AlexsJones** [comment]
> It appears we have a consensus https://github.com/open-feature/community/blob/main/governance-charter.md#decision-making. There's not been a single objection.
> 
> I propose we add @AlexsJones to this PR: https://github.com/open-feature/community/pull/112/files by @AloisReitbauer , then we can close this issue.

https://github.com/open-feature/community/pull/115
