### ISSUE TITLE
Define the final governance model

### ISSUE THREAD

**Issue by oleg-nenashev** [open-feature/community#11]
#1 defines only the bootstrap governance document. We will still need to create a full fledged governance model once the project is fully initialized and founding members are identified,

What is needed

- [x] Technical steering committee
- [x] Governance board (if not merged in the steering committee)
- [x] Official Maintainer roles for the specification, core service and integrations
- [x] Official Project Member role
- [x] Contributor ladder, including qualifications and the approval process
- [ ] ~TBD: Advisory board~
- [ ] ~TBD: Outreach/Events committee~

**Comment by AnaisUrlichs** [comment]
Are these roles that are required e.g. by projects within the CNCF?

**Comment by AloisReitbauer** [comment]
Just to be clear https://github.com/open-feature/community/blob/main/governance-charter.md as never really voted on

**Comment by AloisReitbauer** [comment]
> Are these roles that are required e.g. by projects within the CNCF?

No, they are not but they are quite best practice in other projects like OpenTelemetry

**Comment by AloisReitbauer** [comment]
I don't see the need for an advisory board or an outreach commttee. We have appointed a community manager though.
