### ISSUE TITLE
Restructure community site

### ISSUE THREAD

**Issue by AloisReitbauer** [open-feature/community#111]
I would like to restructure the current community site be similar to OpenTelemetry. They have quite a good practice and structure that will serve as well, too.

Reference: https://github.com/open-telemetry/community

**Comment by beeme1mr** [comment]
The GC and TSC members are listed in multiple locations and should be consolidated as part of this restructuring.

Examples:

- https://github.com/open-feature/community/blob/main/community-members.md#governance-board
- https://github.com/open-feature/community/blob/main/governance-charter.md#tsc-members

**Comment by DavidPHirsch** [comment]
@beeme1mr https://github.com/open-feature/community/pull/146

**Comment by DavidPHirsch** [comment]
All the documents exist and just need to gradually improved and adapted
