### ISSUE TITLE
Social media posts

### ISSUE THREAD

**Issue by Giulia-dipietro** [open-feature/community#128]
Please add below any links to information you'd like to share on the OpenFeature social media profiles (Twitter & Linkedin). 

Don't forget to add your social media handles for tagging.

**Comment by AlexsJones** [comment]
Kubecon talk about OpenFeature is available now on YT -> https://youtu.be/zS6Abop1RJY

**Comment by Giulia-dipietro** [comment]
Alex Jones has joined our Governance board

**Comment by toddbaert** [comment]
We have a tutorial on using the cloud native components (OpenFeature operator + flagd) here: https://docs.openfeature.dev/docs/tutorials/ofo.

It will likely be updated soon with helm installation instructions, but there's no reason we can't promote it independently of that.

**Comment by toddbaert** [comment]
For Go, the maintainers of [flipt](https://www.flipt.io/) recently added a [flipt](https://docs.openfeature.dev/docs/reference/technologies/server/go) provider. For JS, the community added a [PostHog](https://docs.openfeature.dev/docs/reference/technologies/server/javascript) provider, which can be seen in our catalog at the respective places.

**Comment by justinabrahms** [comment]
https://thenewstack.io/ebay-betting-on-open-source-is-great-for-your-business/ - This mentions openfeature which you may want to link to somewhere. Twitter link: https://twitter.com/thenewstack/status/1592220608133500928

**Comment by Giulia-dipietro** [comment]
Announce Alois as governance committee member

**Comment by toddbaert** [comment]
We have 2 new tutorials: getting started with [Java](https://docs.openfeature.dev/docs/tutorials/getting-started/java) and [JS](https://docs.openfeature.dev/docs/tutorials/getting-started/node)

**Comment by beeme1mr** [comment]
Thanks to @tcarrio, OpenFeature now has a PHP SDK! 

https://docs.openfeature.dev/docs/reference/technologies/server/php

**Comment by thomaspoignant** [comment]
[GO Feature Flag](https://gofeatureflag.org) has now a `.NET` provider available.

Some associated links:
provider link: https://www.nuget.org/packages/OpenFeature.Contrib.GOFeatureFlag
repository: https://github.com/thomaspoignant/go-feature-flag
Website: https://gofeatureflag.org/
Doc: https://docs.gofeatureflag.org/
Twitter: @gofeatureflag

**Comment by beeme1mr** [comment]
OpenTelemetry added feature flag semantic conventions to their spec.

https://github.com/open-telemetry/opentelemetry-specification/pull/2529

**Comment by Giulia-dipietro** [comment]
Reminder that the meeting on the 23rd is not a typical one.

**Comment by Giulia-dipietro** [comment]
OpenFeature Happy Holidays post

**Comment by Giulia-dipietro** [comment]
Closing this issue for 2022 - will reopen after the holidays.
