### ISSUE TITLE
request: new membership

### ISSUE THREAD

**Issue by Arhell** [open-feature/community#134]
### GitHub Username

@Arhell

### List of contributions to the open-feature project

https://github.com/open-feature/openfeature.dev/issues/created_by/Arhell
https://github.com/open-feature/openfeature.dev/issues?q=is%3Aissue+author%3AArhell

https://github.com/open-feature/openfeature.dev/commits?author=Arhell

I want to support the project and help fix bugs and other problems that I find.

https://github.com/open-feature/openfeature.dev
https://github.com/open-feature/docs.openfeature.dev

Thank you for your attention

**Comment by beeme1mr** [comment]
Hi @Arhell, thanks for all your help recently and thanks for your interest in the project.

Would you be willing to add yourself to the interested parties list?

https://github.com/open-feature/community/blob/main/interested-parties.md

By the way, we're considering revamping the main landing page. Would you be interested in helping with that initiative?

**Comment by Arhell** [comment]
> Hi @Arhell, thanks for all your help recently and thanks for your interest in the project.
> 
> Would you be willing to add yourself to the interested parties list?
> 
> https://github.com/open-feature/community/blob/main/interested-parties.md
> 
> By the way, we're considering revamping the main landing page. Would you be interested in helping with that initiative?

That would be great, I would love to participate.
