### ISSUE TITLE
Kubecon EU - Talk tracking

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/community#139]
Hi Everyone ,

let's use this issue to track all the CFPs that have been submitted for Kubecon EU.
It would be great if you could share the title.
Please let know if you have any questions.

**Comment by beeme1mr** [comment]
@toddbaert and I submitted a proposal titled: `Commit to Feature Flags: Safely Release and Manage New Features Using GitOps`

**Comment by DavidPHirsch** [comment]
submitted and: `How to open source a project and possibly not fail while trying` - some mentions of Open Feature

**Comment by agardnerIT** [comment]
`OpenFeature: Gracefully and Safely Outgrow In-House Feature Flag Solutions`
