### ISSUE TITLE
Social media posts

### ISSUE THREAD

**Issue by Giulia-dipietro** [open-feature/community#149]
Please add links below to the information you'd like to share on the OpenFeature social media profiles (Twitter & Linkedin).

Remember to add your social media handles for tagging.

**Comment by beeme1mr** [comment]
Getting started guide for the Go SDK.
https://docs.openfeature.dev/docs/tutorials/getting-started/go

**Comment by beeme1mr** [comment]
Go Feature Flag has released an OpenFeature Provider for the Go SDK.
https://docs.openfeature.dev/docs/reference/technologies/server/go

Thanks @thomaspoignant! Please `@` mention [Go Feature Flag](https://twitter.com/gofeatureflag).

**Comment by toddbaert** [comment]
We merged a Flagsmith provider for Java. It will appear [here](https://docs.openfeature.dev/docs/reference/technologies/server/java/) when [this](https://github.com/open-feature/docs.openfeature.dev/pull/250) is merged.

Please wait for [this](https://github.com/open-feature/docs.openfeature.dev/pull/250) PR to be merged before announcing (likely it will be by Monday).

**Comment by toddbaert** [comment]
We have another meeting dedicated to enhancing our specification to support client use-cases, this time at 1PM ET, Friday Jan 20th.

See it in the cal: https://calendar.google.com/calendar/u/0?cid=MHVhN2kxaGl2NWRoMThiMjd0b2FoNjM2NDRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by beeme1mr** [comment]
@josecolella wrote a blog on how we added flagd to homebrew.

https://medium.com/@colellajosemiguel/flagd-formula-my-first-contribution-to-the-homebrew-project-ab33dba470e8

**Comment by toddbaert** [comment]
We have an awesome [blog post](https://docs.openfeature.dev/blog/catering-to-the-client-side/) by @moredip explaining our efforts to develop client-focused additions to the spec, and a link to our [survey](https://forms.gle/TD4gAYKNgPiiwPrd6).

**Comment by toddbaert** [comment]
We have a new flagd provider for .NET: https://docs.openfeature.dev/docs/reference/technologies/server/dotnet

**Comment by Giulia-dipietro** [comment]
Alex Jones' talk at KubeCon: https://kccnceu2023.sched.com/event/1HyWF/building-a-kubernetes-experimentation-platform-with-openfeature-enabling-organisations-to-put-theory-into-practice-alexander-simon-jones-canonical?iframe=no
