### ISSUE TITLE
GSoC OpenFeature - Projects and mentors

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/community#153]
Please use this template.
#### Title

- Description: (2-5+ sentences)
- Expected outcome:
- Recommended Skills:
- Mentor(s): (Name, github, email)
- Expected project size: (175 or 350 Hours)
- Difficulty: (Easy, Medium, or Hard)
- Upstream Issue (URL):

**Comment by beeme1mr** [comment]
https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md#openfeature
