### ISSUE TITLE
OpenFeature & GSoD

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/community#157]
I’d like to propose that OpenFeature participates in the Google Summer of Docs project.

I’m  happy to mentor a project.

**Comment by beeme1mr** [comment]
Did you have a project in mind?

**Comment by BahubaliYh** [comment]
I can help on the front-end side. I have experience in HTML, CSS, and React JS.

**Comment by beeme1mr** [comment]
Hey @agardnerIT, did you end up submitting a proposal for GSoD?
