### ISSUE TITLE
Establish regular project meetings

### ISSUE THREAD

**Issue by oleg-nenashev** [open-feature/community#17]
We need regular project meetings. Until we have a charter on https://community.cncf.io/, we can use individual zoom accounts

- [x] - Agree on the timeslot: https://doodle.com/poll/tvncfguy3wxyhqma?utm_source=poll&utm_medium=link
- [x] - Update contributing guidelines with the meeting info
- [x] - Created a Google Doc for meeting notes
- [x] - Announce the first meeting

**Comment by oleg-nenashev** [comment]
So the first meeting will take place on Thursday, Mar 03, 3PM UTC.
I will send out the invites tonight

**Comment by DavidPHirsch** [comment]
We are still waiting for replies to our doodle to plan the net meetings https://doodle.com/meeting/participate/id/Rb42ZP6e

**Comment by oleg-nenashev** [comment]
done
