### ISSUE TITLE
Define project logo

### ISSUE THREAD

**Issue by oleg-nenashev** [open-feature/community#18]
The project needs a logo. Temporary logo for bootstrap:

![image](https://user-images.githubusercontent.com/3000480/153605937-ce787a16-1d49-457a-89bb-05481617f4a4.png)

**Comment by beeme1mr** [comment]
I was experimenting with a logo design that combines an actual flag with the project name. I'm not a designer but perhaps something like this would work.

![Screen Shot 2022-03-18 at 9 38 10 AM (2)](https://user-images.githubusercontent.com/682996/160914883-021cbfcd-50b7-46db-8997-7f22104f6acc.png)

**Comment by beeme1mr** [comment]
I'm personally not a huge fan of the light switch. It implies boolean logic when a feature flag can be much more than that.

**Comment by beeme1mr** [comment]
I've been working on another potential option for the OpenFeature logo. The `O` is represented by a toggle and the position of the toggle affects the logo color.

Light mode:
![light-mode](https://user-images.githubusercontent.com/682996/166284919-2af774fd-e55a-4b87-bc15-8073417a1b05.png)

Dark mode:
![dark-mode](https://user-images.githubusercontent.com/682996/166284865-2c7b4e8d-8066-49c2-b0f3-87c59ec8e708.png)

We'll still need a smaller icon that can be used for the favicon.

Feedback would be appreciated.

**Comment by beeme1mr** [comment]
# OpenFeature Logo

Here are the proposed logos for OpenFeature. There are two different variations: a light mode and a dark mode.

> NOTE: You must toggle your GitHub theme preferences to see the other version.

## Icon
<img src="https://user-images.githubusercontent.com/682996/167474987-75a13c73-a0b6-4b7d-a5a6-be68a6c70bfb.svg#gh-dark-mode-only" height="24">
<img src="https://user-images.githubusercontent.com/682996/167474992-793eca8c-9859-4791-b0e6-d0492fe4cd59.svg#gh-light-mode-only" height="24">

## Stacked
<img src="https://user-images.githubusercontent.com/682996/167474985-cdb887e6-7e26-45aa-bb8c-b6e60b0cecba.svg#gh-dark-mode-only" height="256">
<img src="https://user-images.githubusercontent.com/682996/167474986-9ad69f15-8b41-4b11-89c1-aaa6b8539254.svg#gh-light-mode-only" height="256">

## Horizontal
<img src="https://user-images.githubusercontent.com/682996/167474988-cd640d6c-59a0-42d8-8060-65536a533e36.svg#gh-dark-mode-only" height="512">
<img src="https://user-images.githubusercontent.com/682996/167474989-738f3b93-6a7d-4c92-a3ec-74f73fae3608.svg#gh-light-mode-only" height="512">
