### ISSUE TITLE
Extract Tooling into own repository

### ISSUE THREAD

**Issue by aepfli** [open-feature/community#180]
# Description

We have merged our peribolos-based configuration recently, and it is doing great work. But unfortunately, as this tooling resides within this repository, we're also getting updates via renovate for our tooling.
This repository should handle community-specific agendas, and managing software updates is more bloat than benefiting the purpose.

So we'd like to extract the tooling into a separate repository, but create deliverable artifacts to be used within the community repository

## Proposal

Migrate the go files into an own repository, and build a docker image within this repository.
This docker image should be ready for GitHub Action so that we can replace the logic of the tooling within this repository within the docker image.

**Comment by AloisReitbauer** [comment]
As discussed via Slack. This will help to keep the repo "clean" from renovate PRs etc.

**Comment by aepfli** [comment]
this is a first iteration: https://github.com/open-feature-forking/community-tooling - i will coordinate with @beeme1mr regarding next steps :)
