### ISSUE TITLE
REQUEST: New membership for mihirm21

### ISSUE THREAD

**Issue by mihirm21** [open-feature/community#208]
### GitHub Username

@mihirm21 

### Requirements

- [x] I have reviewed the community membership guidelines https://github.com/open-feature/community/CONTRIBUTOR_LADDER.md
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/C0344AANLA1) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenFeature subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have created a pull request, adding myself to the `members` of the organization within the [community configuration](https://github.com/open-feature/community/blob/main/config/open-feature/org/workgroup.yaml)

### Sponsors

- @toddbaert
- @beeme1mr

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsor's confirmation before submitting the request.

### List of contributions to the OpenFeature project

- PRs reviewed/authored: https://github.com/open-feature/flagd/pull/322
- Issues responded to: https://github.com/open-feature/flagd/issues/237
                                     https://github.com/open-feature/flagd/issues/298
- Subprojects I am involved with: https://github.com/open-feature/ofep/issues/48 under GSoC '23

**Comment by beeme1mr** [comment]
Hey @mihirm21, welcome! Please add yourself to the member list found [here](https://github.com/open-feature/community/blob/main/config/open-feature/org.yaml#L29). Once merged, that will add you as a member of the org.

**Comment by beeme1mr** [comment]
Please indicate the requirements that you've already addressed by checking the box.
