### ISSUE TITLE
 REQUEST: New membership for @sheepduke

### ISSUE THREAD

**Issue by sheepduke** [open-feature/community#248]
### GitHub Username

@sheepduke

### Requirements

- [x] I have reviewed the community membership guidelines https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md
- [x] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
- [x] I have subscribed to the [Slack channel](https://cloud-native.slack.com/archives/C0344AANLA1) (use http://slack.cncf.io/ to get an invite)
- [x] I am actively contributing to 1 or more OpenFeature subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines. Among other requirements, sponsors must be approvers or maintainers of at least one repository in the organization and not both affiliated with the same company
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have created a pull request, adding myself to the `members` of the organization within the [community configuration](https://github.com/open-feature/community/blob/main/config/open-feature/org/workgroup.yaml)

### Sponsors

- @beeme1mr
- @justinabrahms 

Each sponsor should reply to this issue with the comment "*I support*".
Please remember, it is an applicant's responsibility to get their sponsors confirmation before submitting the request.

### List of contributions to the OpenFeature project

- PRs reviewed / authored https://github.com/open-feature/rust-sdk/pull/15
- Issues responded to:
  - https://github.com/open-feature/rust-sdk/issues/6
  - https://github.com/open-feature/rust-sdk/issues/12
  - https://github.com/open-feature/rust-sdk/issues/13
- Subprojects I am involved with https://github.com/open-feature/rust-sdk

**Comment by beeme1mr** [comment]
I support adding @sheepduke to the org.

**Comment by beeme1mr** [comment]
@justinabrahms would you mind also being a sponsor?

**Comment by justinabrahms** [comment]
> @justinabrahms would you mind also being a sponsor? 

Happy to be. :)

**Comment by justinabrahms** [comment]
If it wasn't obvious, I support.
