### ISSUE TITLE
2023 OpenFeature Governance Committee Elections

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/community#262]
Issue to track the 2023 elections

For information on the election process, see: https://github.com/open-feature/community/blob/main/Elections/2023/Election-Guidelines.md 

If you want to nominate yourself or someone else, open a PR to https://github.com/open-feature/community/blob/main/Elections/2023/Candidates.md  with the following details: 
* Full name
* GitHub alias
* Company affiliation (if applicable)
* Short bio or reasoning to join the Governance Committee (no more than a short paragraph)
* _Optional_: photo/picture of a nominee

**Comment by staceypotter** [comment]
@DavidPHirsch I'm showing these links above as broken: 
- https://github.com/open-feature/community/Elections/2023/Election-Guidelines
- https://github.com/open-feature/community/Elections/2023/Candidates

**Comment by thomaspoignant** [comment]
@DavidPHirsch the links are broken.

**Comment by DavidPHirsch** [comment]
@aepfli @agardnerIT @agentgonzo @ajhelsby @AlexsJones @alina-v1 @AloisReitbauer @AnaisUrlichs @Arhell @ARobertsCollibra @bacherfl @beeme1mr @benjiro @Billlynch @c4milo @Calibretto @cdonnellytx @craigpastro @dabeeeenster @davejohnston @DBlanchard88 @dgorton @dlopes7 @dnsmichi @dominikhaska @dyladan @fabriziodemaria @faulkt @federicobond @gagantrivedi @heckelmann @hlipsig @InTheCloudDan @ivarconr @jakedoublev @jamescarr @james-milligan @jonathannorris @josecolella @jrydberg @justaugustus @justinabrahms @kamil-nowosad @Kavindu-Dodan @kbychu @kinyoklion @konradjniemiec @liran2000 @lopitz @lukas-reining @madhead @markphelps @matthewelwell @mfranberg @mihirm21 @miigwi @mkorbi @moredip @mowies @mschoenlaub @nicklasl @nickybondarenko @nikolasleblanc @odubajDT @oleg-nenashev @oxddr @patricioe @rcrowe @RealAnna @rgrassian-split @rschosser @sago2k8 @salaboy @sheepduke @sighphyre @Sindhuinti @skyerus @s-sen @tcarrio @technicalpickles @tegenterter @therealmitchconnors @thisthat @thiyagu06 @thomaspoignant @thschue @toddbaert @tomkerkhove @vahidlazio @vpetrusevici @weyert

**Comment by DavidPHirsch** [comment]
@madhead @markphelps @matthewelwell @mfranberg @mihirm21 @miigwi @mkorbi @moredip @mowies @mschoenlaub @nicklasl @nickybondarenko @nikolasleblanc @odubajDT @oleg-nenashev @oxddr @patricioe @rcrowe @RealAnna @rgrassian-split @rschosser @sago2k8 @salaboy @sheepduke @sighphyre @Sindhuinti @skyerus @s-sen @tcarrio @technicalpickles @tegenterter @therealmitchconnors @thisthat @thiyagu06 @thomaspoignant @thschue @toddbaert @tomkerkhove @vahidlazio @vpetrusevici @weyert

**Comment by staceypotter** [comment]
📣 Due to a technical error on our part, any prior ballots cast for the Governance Committee Elections via our prior helios voting link are invalid. 🙅 

🗳️ We have resolved the issue, and are asking anyone who previously voted to cast their ballot again using this [new helios voting link](https://vote.heliosvoting.org/helios/elections/765b99df-f00a-4bd5-a885-f014e0f6d625/view) instead. 🗳️ 

We have also updated our [Election Guidelines](https://github.com/open-feature/community/blob/main/Elections/2023/Election-Guidelines.md). We apologize for any inconvenience, and appreciate your understanding in ensuring a fair election process.

**Comment by staceypotter** [comment]
Janek Łukaszewics (@oxddr) has withdrawn his candidacy. I have added PR #336 to list him as "withdrawn" since we cannot alter the ballots once they're opened. Thanks

**Comment by ivarconr** [comment]
I am unable to follow the new link (old one works fine for me). I am being asked to log in to a private area, even though I am already logged in. 

![Screenshot_20240122_225953_Chrome](https://github.com/open-feature/community/assets/158948/56f0d4aa-344c-4435-a3b3-ce3a29c69f4a)

**Comment by staceypotter** [comment]
> I am unable to follow the new link (old one works fine for me). I am being asked to log in to a private area, even though I am already logged in.
> 
> ![Screenshot_20240122_225953_Chrome](https://private-user-images.githubusercontent.com/158948/298741362-56f0d4aa-344c-4435-a3b3-ce3a29c69f4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjQ0MjcsIm5iZiI6MTcwNTk2NDEyNywicGF0aCI6Ii8xNTg5NDgvMjk4NzQxMzYyLTU2ZjBkNGFhLTM0NGMtNDQzNS1hM2IzLWNlM2EyOWM2OWY0YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQyMjU1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzc4NmQwNDVjMGE0MzdjMjkwZjMwOWQ5M2FjNDEwZDkzNzgzNmQ4Y2ZkOGQ1NjE4YzI2NjY1YmU5OTlmOWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JV_jPzdX2ygjPf_a4v4J2swFfq-kCKbCyYtUn_C5J4M)

Let me check the roster of voters and ensure you're listed there. I'll get back to you asap @ivarconr

**Comment by DavidPHirsch** [comment]
@ivarconr should be fixed. please put in a request to join the org

**Comment by staceypotter** [comment]
Drew Gorton (@dgorton) has withdrawn his candidacy. I have added PR #337 to list him as "withdrawn" since we cannot alter the election/ballots once they're opened.

**Comment by staceypotter** [comment]
I suggest we also post in slack and socials to make the elections process clear:
1. Noting that no withdrawn candidates votes may be transferred to other candidates
2. Any org member who has previously voted may recast their ballot - if they so choose to do so - via helios (only the latest ballot cast counts)
3. Our elections are based on approval voting which we've described in our [Election Guidelines here](https://github.com/open-feature/community/blob/main/Elections/2023/Election-Guidelines.md#vote).

Does this make sense? Anything else I'm missing?

**Comment by DavidPHirsch** [comment]
Congratulations @AloisReitbauer @dabeeeenster @beeme1mr @moredip @jrydberg @jonathannorris  @weyert
