### ISSUE TITLE
Setup communication channels for the project

### ISSUE THREAD

**Issue by oleg-nenashev** [open-feature/community#3]
We need Slack channels (on Kubernetes or CNCF?) and maybe other entries for the project. Not sure about creating a new Slack workspace at the moment.

**Comment by oleg-nenashev** [comment]
Doodle for the kick-off meetings: https://doodle.com/poll/tvncfguy3wxyhqma?utm_source=poll&utm_medium=link

**Comment by DavidPHirsch** [comment]
@beeme1mr and @oleg-nenashev can I close this issue?

**Comment by beeme1mr** [comment]
Sure, I'll go ahead and close it.
