### ISSUE TITLE
Vendor Outreach

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/community#31]
We should reach out to all of the vendors (and open source projects) in the flagging space. We'd like to let them know what we're doing, see if they want to get involved, etc.

The list:

| Status | Company | Company Representative | Outreach Lead | Comment|
| --- | --- | --- | --- | --- |
| :green_square: | cloudbees | @agentgonzo  | @beeme1mr  |  |
| :green_square: | flagsmith | @dabeeeenster | @beeme1mr  |  |
| :green_square: | launch darkly | @intheclouddan  | @AloisReitbauer  |  |
| :yellow_square: | optimizely |  |  |  |
| :green_square:  | split.io | @patricioe | @beeme1mr  |  |
| :green_square: | harness | @davejohnston | @beeme1mr  |  |
| :yellow_square: | apptimize |  |  |  |
| :green_square: | configcat | @sigewuzhere |  |  |
| :green_square: | unleash | @ivarconr | @beeme1mr   |  |

Key:
| Status | Meaning |
| --- | --- |
| :green_square: | Interested party |
| :blue_square: | Communication has been established |
| :yellow_square: | No contact yet |

**Comment by kbychu** [comment]
- [ ] Unleash

**Comment by beeme1mr** [comment]
Should we move this to a markdown page?

**Comment by beeme1mr** [comment]
@justinabrahms [Optimizely](https://www.optimizely.com/) has Ebay listed as a customer. Any chance you could help make the connection?

**Comment by justinabrahms** [comment]
@beeme1mr I'll try to track down contacts.

**Comment by justinabrahms** [comment]
I've reached out to our optimizely contact. They passed the information along to engineering.. but I don't have contact info for the relevant folks. maybe @davidvc might know of someone?

**Comment by davidvc** [comment]
I just checked, and in the 1.5 years since I was there, literally everyone I know has left...  Sorry!

**Comment by kbychu** [comment]
I have a contact at Unleash and will reach out

**Comment by weyert** [comment]
You might want to consider reaching out to @jamesefhawkins or @timgl from PostHog as they also support feature flags in their product analytics product

**Comment by beeme1mr** [comment]
Hey @justinabrahms, do you think we should close this issue now? We have solid vendor coverage and can continue to add more as we're able to make contact with them.

**Comment by timgl** [comment]
We’re keen to be included. My email is ***@***.***

**Comment by beeme1mr** [comment]
Hi @timgl, could you please open a PR on the [interested party page](https://github.com/open-feature/community/blob/main/interested-parties.md)? It also looks like GitHub obfuscated your email address.
