### ISSUE TITLE
Voting inaccuracies in helios poll

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/community#322]
In the current voting period I am being misrepresented by another GitHub profile which has been reported to me by two Open Feature contributors. I would like to ask for this to be amended and possibly resuggest we have a new voting period due to spoilt votes.

https://vote.heliosvoting.org/helios/elections/a15ff6ba-62b9-11ee-bf2b-0680edabc785/questions

<img width="520" alt="Screenshot 2024-01-11 at 15 10 53" src="https://github.com/open-feature/community/assets/1235925/413fe2fe-5dc3-4c8c-a42e-59ca936ca8da">

**Comment by beeme1mr** [comment]
I think we should correct this issue and review the existing governance seats.

**Comment by dabeeeenster** [comment]
I am on the same board and concur with the above; please can we have a new voting period, thanks.

**Comment by toddbaert** [comment]
> I would like to ask for this to be amended and possibly resuggest we have a new voting period due to spoilt votes.

Not on the GC, but I definitely agree.

**Comment by justinabrahms** [comment]
On the board. I'll stay in office for a little while longer. ;)  This new voting thing is fine w/ me.

**Comment by moredip** [comment]
agreed

**Comment by DavidPHirsch** [comment]
- new voting link has been created https://vote.heliosvoting.org/helios/elections/765b99df-f00a-4bd5-a885-f014e0f6d625/view please review
- there will be an announcement on slack and social media
- the election guidelines and issues will be updated
- all those that already voted will be contacted directly to vote again
anything missing?

**Comment by staceypotter** [comment]
Elections guidelines update PR #324.
