### ISSUE TITLE
Project video forKubecon EU 2024

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/community#329]
Hello,

we have the opportunity to send in a project video for Kubecon EU. the deadline is January 27th.
Anyone able to take some time for this?

**Comment by DavidPHirsch** [comment]
Project Updates Keynote - Video Submissions
We are excited to offer the opportunity to submit a short 'project updates' video to announce at KubeCon + CloudNativeCon Europe 2024! Our goal is to provide a platform on the keynote stage to amplify the voices in the community through a visual medium.

Based on feedback from the community, we are putting a heavy focus on consistency and quality to ensure your message is clear and effective on the Keynote stage. 

We ask that all submitters adhere to the established guidelines below. If you do not meet these requirements, you will be asked to resubmit:
When recording, [you must follow these guidelines](https://drive.google.com/file/d/1-F9keb67pQprFY_zJMQtnvBIYvw8xivK/view?usp=sharing) to ensure your audio and video quality meet expectations. If you have any questions about these guidelines, please reach out to CNCF Ambassador James Spurin in the [#cncf-project-updates-keynote](https://cloud-native.slack.com/archives/C05D2JYTG05) public slack channel.
All videos must not exceed 1 minute.
You must submit a separate slide deck with your updates using [our keynote ready, high-resolution template.](https://docs.google.com/presentation/d/1ZClGvlcv2gZ0XYNA982PEQ2eVx9Dfbnz/edit?usp=sharing&ouid=104241342834088258023&rtpof=true&sd=true)
Any Call to Action needs to be clear with concise links and/or QR codes.
Your video and slide deck must be submitted by Thursday, 25 January in order to be considered.

We encourage you to take advantage of this opportunity to showcase your project and we're happy to answer any questions you have. Please feel free to reach out to [speakers@cncf.io](mailto:speakers@cncf.io).

**Comment by beeme1mr** [comment]
Unfortunately, this is only available for projects that have graduated.
