### ISSUE TITLE
CNCF Sandbox project application

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/community#39]
The proposal process can be found here:
https://github.com/cncf/toc/blob/main/process/project_proposals.adoc

**Comment by kbychu** [comment]
@beeme1mr the link leads to a 404 for me. DId you mean https://github.com/cncf/toc/blob/main/process/sandbox.md ?

Is there anything I can help with?

**Comment by beeme1mr** [comment]
@kbychu the link should be valid. Are you still having trouble accessing it?

The application has been submitted. We're just waiting for a response. In the meantime, we're hoping to put together a joint press release that we could use to help push the process along.

**Comment by justinabrahms** [comment]
Actual request has made it into this google doc: https://docs.google.com/spreadsheets/d/1Nnh_usr0tSZxaUpxTusqeIqKxMmvuEViRkyO9e_Do40/edit#gid=1398510353

**Comment by beeme1mr** [comment]
The project has been accepted in the CNCF. Onboarding can be tracked [here](https://github.com/cncf/toc/issues/857).
