### ISSUE TITLE
🗳️ VOTE: Bootstrap Technical Steering Committee

### ISSUE THREAD

**Issue by oleg-nenashev** [open-feature/community#48]
As agreed at the project meeting on April 14 and discussed before on Slack, we want to proceed with the Technical Steering Committee entity and with appointing the bootstrap members.

Proposal for voting:

- Approve the Technical Steering Proposal https://github.com/open-feature/community/pull/46. As agreed at the meeting, we can extend the committee later as needed
- Appoint the bootstrap technical steering committee
  - Todd Baert, Dynatrace
  - Steve Arch, CloudBees
  - Dan O’Brien, LaunchDarkly

Please vote 👍/👎 in this issue or comment below. Any community member can vote.

**Comment by DavidPHirsch** [comment]
all connected issues and PRs are closed
