### ISSUE TITLE
KubeCon NA 2022 - Kiosk and SWAG for Open Feature

### ISSUE THREAD

**Issue by DavidPHirsch** [open-feature/community#96]
Hi Everyone,

as we will have a Kiosk for Open Feature at kubecon it would be useful to know who all will be there so we can have it covered fro the whole conference. If you could add the dates you will be there and your availability we can coordinate.
Also it would be nice to have some SWAG to give away, would anyone be interested in participating here? @beeme1mr had already found a good supplier for Kubecon EU.

**Comment by beeme1mr** [comment]
We should be good to go for KubeCon.
